"""add share_count and articleview

Revision ID: 135ccdbb00a0
Revises: e5f6g7h8i9j0
Create Date: 2026-02-03 01:57:32.018220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '135ccdbb00a0'
down_revision: Union[str, None] = 'e5f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articleview',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articleview_article_id'), 'articleview', ['article_id'], unique=False)
    op.create_index(op.f('ix_articleview_viewer_hash'), 'articleview', ['viewer_hash'], unique=False)
    op.add_column('article', sa.Column('share_count', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('fk_article_created_by'), 'article', type_='foreignkey')
    op.drop_constraint(op.f('fk_article_updated_by'), 'article', type_='foreignkey')
    op.drop_constraint(op.f('articlelike_article_id_fkey'), 'articlelike', type_='foreignkey')
    op.drop_constraint(op.f('articlelike_user_id_fkey'), 'articlelike', type_='foreignkey')
    op.create_foreign_key(None, 'articlelike', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'articlelike', 'article', ['article_id'], ['id'])
    op.alter_column('comment', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint(op.f('comment_parent_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_article_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_user_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('passwordresettoken_user_id_fkey'), 'passwordresettoken', type_='foreignkey')
    op.create_foreign_key(None, 'passwordresettoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passwordresettoken', type_='foreignkey')
    op.create_foreign_key(op.f('passwordresettoken_user_id_fkey'), 'passwordresettoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_user_id_fkey'), 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comment_article_id_fkey'), 'comment', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comment_parent_id_fkey'), 'comment', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comment', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'articlelike', type_='foreignkey')
    op.drop_constraint(None, 'articlelike', type_='foreignkey')
    op.create_foreign_key(op.f('articlelike_user_id_fkey'), 'articlelike', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('articlelike_article_id_fkey'), 'articlelike', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_article_updated_by'), 'article', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_article_created_by'), 'article', 'user', ['created_by'], ['id'])
    op.drop_column('article', 'share_count')
    op.drop_index(op.f('ix_articleview_viewer_hash'), table_name='articleview')
    op.drop_index(op.f('ix_articleview_article_id'), table_name='articleview')
    op.drop_table('articleview')
    # ### end Alembic commands ###
