"""add cover_public_id to article

Revision ID: 063456035ff3
Revises: 30abec4bcfae
Create Date: 2026-02-02 04:52:11.217491
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '063456035ff3'
down_revision: Union[str, None] = '30abec4bcfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('avatar_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'avatar_public_id')
    op.drop_column('article', 'cover_public_id')
    # ### end Alembic commands ###
