"""add notifications tables

Revision ID: 88114221b708
Revises: 7457493ad677
Create Date: 2026-02-03 17:38:51.082271
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88114221b708'
down_revision: Union[str, None] = '7457493ad677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('notificationpreferences',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('in_app_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_notifications', sa.Boolean(), nullable=False),
    sa.Column('security_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificationpreferences_user_id'), 'notificationpreferences', ['user_id'], unique=True)
    # op.drop_table('publisher_requests')  # This was incorrectly generated
    # Check if table exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'publisher_requests' in inspector.get_table_names():
        op.drop_table('publisher_requests')
    # op.alter_column('article', 'is_featured',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('article', 'is_pinned',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_article_status_created'), table_name='article')
    op.drop_index(op.f('ix_articlelike_composite'), table_name='articlelike')
    op.drop_constraint(op.f('articlelike_article_id_fkey'), 'articlelike', type_='foreignkey')
    op.drop_constraint(op.f('articlelike_user_id_fkey'), 'articlelike', type_='foreignkey')
    op.create_foreign_key(None, 'articlelike', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'articlelike', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_articleview_composite'), table_name='articleview')
    op.drop_constraint(op.f('articleview_article_id_fkey'), 'articleview', type_='foreignkey')
    op.create_foreign_key(None, 'articleview', 'article', ['article_id'], ['id'])
    op.alter_column('comment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_comment_article_created'), table_name='comment')
    op.drop_constraint(op.f('comment_parent_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_user_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_article_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    # op.alter_column('user', 'role',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False,
    #            existing_server_default=sa.text("'user'::character varying"))
    # op.alter_column('user', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=False,
    #            existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_article_id_fkey'), 'comment', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comment_user_id_fkey'), 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comment_parent_id_fkey'), 'comment', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_comment_article_created'), 'comment', ['article_id', 'created_at'], unique=False)
    op.alter_column('comment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'articleview', type_='foreignkey')
    op.create_foreign_key(op.f('articleview_article_id_fkey'), 'articleview', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_articleview_composite'), 'articleview', ['article_id', 'viewer_hash', 'viewed_at'], unique=False)
    op.drop_constraint(None, 'articlelike', type_='foreignkey')
    op.drop_constraint(None, 'articlelike', type_='foreignkey')
    op.create_foreign_key(op.f('articlelike_user_id_fkey'), 'articlelike', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('articlelike_article_id_fkey'), 'articlelike', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_articlelike_composite'), 'articlelike', ['user_id', 'article_id'], unique=True)
    op.create_index(op.f('ix_article_status_created'), 'article', ['status', 'created_at'], unique=False)
    op.alter_column('article', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('article', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('publisher_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('publisher_requests_pkey'))
    )
    op.drop_index(op.f('ix_notificationpreferences_user_id'), table_name='notificationpreferences')
    op.drop_table('notificationpreferences')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
